# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OpenTokRTC' do

end

target 'OpenTokRTCTests' do

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'OpenTok'
pod 'SwiftHTTP', '~> 0.9.4'
pod 'Alamofire', '~> 1.2'